#!/bin/sh

for d in \
	"/cygdrive/c/Program Files (x86)/Atmel/AVR Tools/AVR32 Toolchain/bin" \
    "/mnt/c/Program Files (x86)/Atmel/AVR Tools/AVR32 Toolchain/bin" \
    ;do
	if [ -d "$d" ]
	then
        echo "Found AVR32BIN directory in"
        echo "$d"
        export AVR32BIN="$d"
	    break
	fi
done

if [ -d "$d" ]
then
    PATH=${AVR32BIN}:$PATH
    export PATH
    cd Release && make all
else
    echo "Could not find AVR32BIN directory"
fi
